CLASS /pyxs/cl_fiscal_documents DEFINITION
PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES: if_oo_adt_classrun,
      if_rap_query_provider.
    TYPES:
      BEGIN OF ty_unidademedidadestino,
        codigo    TYPE string,
        descricao TYPE string,
      END OF ty_unidademedidadestino,


      BEGIN OF ty_unidademedidaorigem,
        codigo    TYPE string,
        descricao TYPE string,
      END OF ty_unidademedidaorigem,


      BEGIN OF ty_conversoesunidademedida,
        unidademedidaorigem  TYPE ty_unidademedidaorigem,
        unidademedidadestino TYPE ty_unidademedidadestino,
        fatorconversao       TYPE string,
        operacaoconversao    TYPE string,
        codigobarras         TYPE string,
      END OF ty_conversoesunidademedida,


      BEGIN OF ty_classificacaoservicoprestad,
        codigo TYPE string,
      END OF ty_classificacaoservicoprestad,


      BEGIN OF ty_cest,
        codigocest TYPE string,
        codigoncm  TYPE string,
        gruponcm   TYPE string,
      END OF ty_cest,


      BEGIN OF ty_classificacaofiscal,
        codigo                 TYPE string,
        codigoexcecaotabelaipi TYPE string,
      END OF ty_classificacaofiscal,


      BEGIN OF ty_origemitem,
        codigo    TYPE string,
        descricao TYPE string,
      END OF ty_origemitem,


      BEGIN OF ty_unidademedida,
        codigo    TYPE string,
        descricao TYPE string,
      END OF ty_unidademedida,


      BEGIN OF ty_item,
        codigo                      TYPE string,
        descricao                   TYPE string,
        unidademedida               TYPE ty_unidademedida,
        origemitem                  TYPE ty_origemitem,
        tipoitem                    TYPE string,
        codigobarra                 TYPE string,
        classificacaofiscal         TYPE ty_classificacaofiscal,
        cest                        TYPE ty_cest,
        codigolistaservico          TYPE string,
        idportalitem                TYPE string,
        aliquotaicms                TYPE p LENGTH 15 DECIMALS 2,
        classificacaoservicoprestad TYPE ty_classificacaoservicoprestad,
        conversoesunidademedida     TYPE STANDARD TABLE OF ty_conversoesunidademedida WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_item,


      BEGIN OF ty_detalhes,
        numerosequencia       TYPE string,
        codigoajustebeneficio TYPE string,
        item                  TYPE ty_item,
        valorbaseicms         TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicms          TYPE p LENGTH 15 DECIMALS 2,
        valoricms             TYPE p LENGTH 15 DECIMALS 2,
        valoroutros           TYPE p LENGTH 15 DECIMALS 2,
        descricaocomplementar TYPE string,
      END OF ty_detalhes,


      BEGIN OF ty_observacaolancamentofiscal,
        codigo    TYPE string,
        descricao TYPE string,
      END OF ty_observacaolancamentofiscal,


      BEGIN OF ty_observacoes,
        observacaolancamentofiscal TYPE ty_observacaolancamentofiscal,
        detalhes                   TYPE STANDARD TABLE OF ty_detalhes WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_observacoes,


      BEGIN OF ty_entrega,
        cpfcnpj             TYPE string,
        inscricaoestadual   TYPE string,
        municipiocodigoibge TYPE string,
      END OF ty_entrega,


      BEGIN OF ty_coleta,
        cpfcnpj             TYPE string,
        inscricaoestadual   TYPE string,
        municipiocodigoibge TYPE string,
      END OF ty_coleta,


      BEGIN OF ty_destinatario,
        cpfcnpj             TYPE string,
        inscricaoestadual   TYPE string,
        municipiocodigoibge TYPE string,
      END OF ty_destinatario,


      BEGIN OF ty_remetente,
        cpfcnpj             TYPE string,
        inscricaoestadual   TYPE string,
        municipiocodigoibge TYPE string,
      END OF ty_remetente,


      BEGIN OF ty_notasfiscaisconhecimentotra,
        tipotransporte    TYPE string,
        modelo            TYPE string,
        serie             TYPE string,
        numero            TYPE string,
        dataemissao       TYPE d,
        valortotal        TYPE p LENGTH 15 DECIMALS 2,
        valormercadoria   TYPE p LENGTH 15 DECIMALS 2,
        quantidadevolumes TYPE string,
        pesobruto         TYPE p LENGTH 15 DECIMALS 2,
        pesoliquido       TYPE p LENGTH 15 DECIMALS 2,
        numerodespacho    TYPE string,
        remetente         TYPE ty_remetente,
        destinatario      TYPE ty_destinatario,
        coleta            TYPE ty_coleta,
        entrega           TYPE ty_entrega,
      END OF ty_notasfiscaisconhecimentotra,


      BEGIN OF ty_obras,
        codigo                         TYPE string,
        nome                           TYPE string,
        tipoprestacaoservicoobraconstr TYPE string,
        inscricaomunicipal             TYPE string,
        codigocno                      TYPE string,
      END OF ty_obras,

      BEGIN OF ty_parceiro,
        codigo                         TYPE string,
        nome                           TYPE string,
        nomefantasia                   TYPE string,
        cnpj                           TYPE string,
        cpf                            TYPE string,
        inscricaoestadual              TYPE string,
        inscricaomunicipal             TYPE string,
        inscricaosuframa               TYPE string,
        codigocnae                     TYPE string,
        indcprb                        TYPE string,
        ativo                          TYPE string,
        endereco                       TYPE string,
        numero                         TYPE string,
        complemento                    TYPE string,
        bairro                         TYPE string,
        cep                            TYPE string,
        paiscodigoibge                 TYPE string,
        municipiocodigoibge            TYPE string,
        ddd                            TYPE string,
        telefone                       TYPE string,
        email                          TYPE string,
        indoptantesimplesnacional      TYPE string,
        indicadornif                   TYPE string,
        nif                            TYPE string,
        indicadorcontribuinteicms      TYPE string,
        indicadorcontribuinteipi       TYPE string,
        codigoformatribrendbeneficiari TYPE string,
        codigoinfbeneficiariosrendex   TYPE string,
        tipoparceiro                   TYPE string,
        tipoclienteicms11503           TYPE string,
        obras                          TYPE STANDARD TABLE OF ty_obras WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_parceiro,


      BEGIN OF ty_parceiroredespeacho,
        codigo                         TYPE string,
        nome                           TYPE string,
        nomefantasia                   TYPE string,
        cnpj                           TYPE string,
        cpf                            TYPE string,
        inscricaoestadual              TYPE string,
        inscricaomunicipal             TYPE string,
        inscricaosuframa               TYPE string,
        codigocnae                     TYPE string,
        indcprb                        TYPE string,
        ativo                          TYPE string,
        endereco                       TYPE string,
        numero                         TYPE string,
        complemento                    TYPE string,
        bairro                         TYPE string,
        cep                            TYPE string,
        paiscodigoibge                 TYPE string,
        municipiocodigoibge            TYPE string,
        ddd                            TYPE string,
        telefone                       TYPE string,
        email                          TYPE string,
        indoptantesimplesnacional      TYPE string,
        indicadornif                   TYPE string,
        nif                            TYPE string,
        indicadorcontribuinteicms      TYPE string,
        indicadorcontribuinteipi       TYPE string,
        codigoformatribrendbeneficiari TYPE string,
        codigoinfbeneficiariosrendex   TYPE string,
        tipoparceiro                   TYPE string,
        tipoclienteicms11503           TYPE string,
        obras                          TYPE STANDARD TABLE OF ty_obras WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_parceiroredespeacho,


      BEGIN OF ty_parceiroconsignatario,
        codigo                         TYPE string,
        nome                           TYPE string,
        nomefantasia                   TYPE string,
        cnpj                           TYPE string,
        cpf                            TYPE string,
        inscricaoestadual              TYPE string,
        inscricaomunicipal             TYPE string,
        inscricaosuframa               TYPE string,
        codigocnae                     TYPE string,
        indcprb                        TYPE string,
        ativo                          TYPE string,
        endereco                       TYPE string,
        numero                         TYPE string,
        complemento                    TYPE string,
        bairro                         TYPE string,
        cep                            TYPE string,
        paiscodigoibge                 TYPE string,
        municipiocodigoibge            TYPE string,
        ddd                            TYPE string,
        telefone                       TYPE string,
        email                          TYPE string,
        indoptantesimplesnacional      TYPE string,
        indicadornif                   TYPE string,
        nif                            TYPE string,
        indicadorcontribuinteicms      TYPE string,
        indicadorcontribuinteipi       TYPE string,
        codigoformatribrendbeneficiari TYPE string,
        codigoinfbeneficiariosrendex   TYPE string,
        tipoparceiro                   TYPE string,
        tipoclienteicms11503           TYPE string,
        obras                          TYPE STANDARD TABLE OF ty_obras WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_parceiroconsignatario,


      BEGIN OF ty_complementosconhecimentotra,
        parceiroconsignatario      TYPE ty_parceiroconsignatario,
        parceiroredespeacho        TYPE ty_parceiroredespeacho,
        municipioorigemcodigoibge  TYPE string,
        municipiodestinocodigoibge TYPE string,
        tipofreteredespacho        TYPE string,
        estadoplacaveiculo         TYPE string,
        placaveiculo               TYPE string,
        valorliquidofrete          TYPE p LENGTH 15 DECIMALS 2,
        valortotalfrete            TYPE p LENGTH 15 DECIMALS 2,
        valorseccat                TYPE p LENGTH 15 DECIMALS 2,
        valordespacho              TYPE p LENGTH 15 DECIMALS 2,
        valorpedagio               TYPE p LENGTH 15 DECIMALS 2,
        valoroutros                TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_complementosconhecimentotra,


      BEGIN OF ty_impostosretidos,
        tipoimposto                TYPE string,
        codigoreceita              TYPE string,
        datavencimento             TYPE d,
        datapagamento              TYPE d,
        valorbaseretencao          TYPE p LENGTH 15 DECIMALS 2,
        aliquotaretencao           TYPE p LENGTH 15 DECIMALS 2,
        valorretido                TYPE p LENGTH 15 DECIMALS 2,
        condicaopessoajuridica     TYPE string,
        sequenciaitem              TYPE string,
        codigoreferenciaintegracao TYPE string,
        varcodreceita              TYPE string,
        naturezarendimento         TYPE string,
        observacao                 TYPE string,
        indicativoorigemrendimento TYPE string,
        cnpjorigemrendimento       TYPE string,
      END OF ty_impostosretidos,


      BEGIN OF ty_parceiros,
        nome                      TYPE string,
        nomefantasia              TYPE string,
        tipoparceiro              TYPE string,
        cnpj                      TYPE string,
        cpf                       TYPE string,
        inscricaoestadual         TYPE string,
        inscricaomunicipal        TYPE string,
        inscricaosuframa          TYPE string,
        endereco                  TYPE string,
        numero                    TYPE string,
        complemento               TYPE string,
        bairro                    TYPE string,
        cep                       TYPE string,
        paiscodigoibge            TYPE string,
        municipiocodigoibge       TYPE string,
        ddd                       TYPE string,
        telefone                  TYPE string,
        email                     TYPE string,
        indicadorcontribuinteicms TYPE string,
        indicadorcontribuinteipi  TYPE string,
      END OF ty_parceiros,


      BEGIN OF ty_informacaocomplementar,
        codigo    TYPE string,
        descricao TYPE string,
        tipo      TYPE string,
      END OF ty_informacaocomplementar,

      BEGIN OF ty_processosreferenciados,
        origem TYPE string,
        numero TYPE string,
      END OF ty_processosreferenciados,

      BEGIN OF ty_cuponsfiscaisreferenciados,
        modelo             TYPE string,
        numerodocumento    TYPE string,
        seriefabricacaoecf TYPE string,
        numerocaixaecf     TYPE string,
        dataemissao        TYPE d,
      END OF ty_cuponsfiscaisreferenciados,


      BEGIN OF ty_documentosfiscaisreferencia,
        operacao        TYPE string,
        emitente        TYPE string,
        parceiro        TYPE ty_parceiro,
        modelo          TYPE string,
        serie           TYPE string,
        subserie        TYPE string,
        numerodocumento TYPE string,
        dataemissao     TYPE d,
        chavenfe        TYPE string,
      END OF ty_documentosfiscaisreferencia,


      BEGIN OF ty_documentosarrecadacaorefere,
        modelo             TYPE string,
        estadobeneficiario TYPE string,
        datavencimento     TYPE d,
        datapagamento      TYPE d,
        numerodocumento    TYPE string,
        codigoautenticacao TYPE string,
        valordocumento     TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_documentosarrecadacaorefere,

      BEGIN OF ty_localcoletaentrega,
        tipotransporte                 TYPE string,
        inscricaoestadualcontribuintec TYPE string,
        cnpjcontribuintecoleta         TYPE string,
        cpfcontribuinte                TYPE string,
        municipiocoletacodigoibge      TYPE string,
        inscricaoestadualcontribuintee TYPE string,
        cnpjcontribuinteentrega        TYPE string,
        cpfcontribuinteentrega         TYPE string,
        municipioentregacodigoibge     TYPE string,
        nomecoleta                     TYPE string,
        enderecocoleta                 TYPE string,
        numerocoleta                   TYPE string,
        complementocoleta              TYPE string,
        bairrocoleta                   TYPE string,
        cepcoleta                      TYPE string,
        telefonecoleta                 TYPE string,
        emailcoleta                    TYPE string,
        nomeentrega                    TYPE string,
        enderecoentrega                TYPE string,
        numeroentrega                  TYPE string,
        complementoentrega             TYPE string,
        bairroentrega                  TYPE string,
        cepentrega                     TYPE string,
        telefoneentrega                TYPE string,
        emailentrega                   TYPE string,
      END OF ty_localcoletaentrega,

      BEGIN OF ty_informacoesadicionais,
        informacaocomplementar         TYPE ty_informacaocomplementar,
        descricaocomplementar          TYPE string,
        processosreferenciados         TYPE STANDARD TABLE OF ty_processosreferenciados WITH NON-UNIQUE DEFAULT KEY,
        documentosarrecadacaoref       TYPE STANDARD TABLE OF ty_documentosarrecadacaorefere WITH NON-UNIQUE DEFAULT KEY,
        documentosfiscaisreferenciados TYPE STANDARD TABLE OF ty_documentosfiscaisreferencia WITH NON-UNIQUE DEFAULT KEY,
        cuponsfiscaisreferenciados     TYPE STANDARD TABLE OF ty_cuponsfiscaisreferenciados WITH NON-UNIQUE DEFAULT KEY,
        localcoletaentrega             TYPE ty_localcoletaentrega,
      END OF ty_informacoesadicionais,


      BEGIN OF ty_fabricante,
        codigo                         TYPE string,
        nome                           TYPE string,
        nomefantasia                   TYPE string,
        cnpj                           TYPE string,
        cpf                            TYPE string,
        inscricaoestadual              TYPE string,
        inscricaomunicipal             TYPE string,
        inscricaosuframa               TYPE string,
        codigocnae                     TYPE string,
        indcprb                        TYPE string,
        ativo                          TYPE string,
        endereco                       TYPE string,
        numero                         TYPE string,
        complemento                    TYPE string,
        bairro                         TYPE string,
        cep                            TYPE string,
        paiscodigoibge                 TYPE string,
        municipiocodigoibge            TYPE string,
        ddd                            TYPE string,
        telefone                       TYPE string,
        email                          TYPE string,
        indoptantesimplesnacional      TYPE string,
        indicadornif                   TYPE string,
        nif                            TYPE string,
        indicadorcontribuinteicms      TYPE string,
        indicadorcontribuinteipi       TYPE string,
        codigoformatribrendbeneficiari TYPE string,
        codigoinfbeneficiariosrendex   TYPE string,
        tipoparceiro                   TYPE string,
        tipoclienteicms11503           TYPE string,
        obras                          TYPE STANDARD TABLE OF ty_obras WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_fabricante,


      BEGIN OF ty_adicao,
        numeroadicao        TYPE string,
        numerosequencia     TYPE string,
        fabricante          TYPE ty_fabricante,
        valordesconto       TYPE string,
        viatransporte       TYPE string,
        valoradicionalfrete TYPE string,
        tipointermediario   TYPE string,
      END OF ty_adicao,


      BEGIN OF ty_exportador,
        codigo                         TYPE string,
        nome                           TYPE string,
        nomefantasia                   TYPE string,
        cnpj                           TYPE string,
        cpf                            TYPE string,
        inscricaoestadual              TYPE string,
        inscricaomunicipal             TYPE string,
        inscricaosuframa               TYPE string,
        codigocnae                     TYPE string,
        indcprb                        TYPE string,
        ativo                          TYPE string,
        endereco                       TYPE string,
        numero                         TYPE string,
        complemento                    TYPE string,
        bairro                         TYPE string,
        cep                            TYPE string,
        paiscodigoibge                 TYPE string,
        municipiocodigoibge            TYPE string,
        ddd                            TYPE string,
        telefone                       TYPE string,
        email                          TYPE string,
        indoptantesimplesnacional      TYPE string,
        indicadornif                   TYPE string,
        nif                            TYPE string,
        indicadorcontribuinteicms      TYPE string,
        indicadorcontribuinteipi       TYPE string,
        codigoformatribrendbeneficiari TYPE string,
        codigoinfbeneficiariosrendex   TYPE string,
        tipoparceiro                   TYPE string,
        tipoclienteicms11503           TYPE string,
        obras                          TYPE STANDARD TABLE OF ty_obras WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_exportador,


      BEGIN OF ty_importacoes,
        numerosequencia   TYPE string,
        numerodi          TYPE string,
        datadi            TYPE d,
        datadesembaraco   TYPE d,
        ufdesembaraco     TYPE string,
        localdesembarque  TYPE string,
        exportador        TYPE ty_exportador,
        cnpjintermediario TYPE string,
        atodrawback       TYPE string,
        adicao            TYPE ty_adicao,
      END OF ty_importacoes,


      BEGIN OF ty_complementorestituicaocompl,
        motivorestituicaocomplementaca TYPE string,
        motivoressarcimento            TYPE string,
        numerosequencia                TYPE string,
        valorunitarioicmsst            TYPE p LENGTH 15 DECIMALS 2,
        valorunitariofcp               TYPE p LENGTH 15 DECIMALS 2,
        valorunitarioicmsstcomplementa TYPE p LENGTH 15 DECIMALS 2,
        valorunitariofcpstcomplementar TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_complementorestituicaocompl,


      BEGIN OF ty_estoque,
        valormediobaseicmsst TYPE p LENGTH 15 DECIMALS 2,
        valormedioicmsst     TYPE p LENGTH 15 DECIMALS 2,
        valormediofcpst      TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_estoque,


      BEGIN OF ty_unidademedidaconversao,
        codigo    TYPE string,
        descricao TYPE string,
      END OF ty_unidademedidaconversao,


      BEGIN OF ty_complemento,
        responsavelretencao            TYPE string,
        modeloarrecadacao              TYPE string,
        numerodocumentoarrecadacao     TYPE string,
        quantidadeconvertida           TYPE p LENGTH 15 DECIMALS 2,
        unidademedidaconversao         TYPE ty_unidademedidaconversao,
        valorunitarioconvertido        TYPE p LENGTH 15 DECIMALS 2,
        valorunitarioicmsconvertido    TYPE p LENGTH 15 DECIMALS 2,
        valorunitariobaseicmsstconvert TYPE p LENGTH 15 DECIMALS 2,
        valorunitarioicmsstconvertido  TYPE p LENGTH 15 DECIMALS 2,
        valorunitariofcpstconvertido   TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_complemento,


      BEGIN OF ty_documentoretencao,
        modelo          TYPE string,
        chavenfe        TYPE string,
        serie           TYPE string,
        numerodocumento TYPE string,
        parceiro        TYPE ty_parceiro,
        numerosequencia TYPE string,
        dataemissao     TYPE d,
      END OF ty_documentoretencao,


      BEGIN OF ty_documentorelativoultimaentr,
        chavenfe                TYPE string,
        modelo                  TYPE string,
        serie                   TYPE string,
        numerodocumento         TYPE string,
        parceiro                TYPE ty_parceiro,
        dataentrada             TYPE d,
        numerosequencia         TYPE string,
        quantidade              TYPE p LENGTH 15 DECIMALS 2,
        valorunitario           TYPE p LENGTH 15 DECIMALS 2,
        valorunitariobaseicmsst TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicmsst          TYPE p LENGTH 15 DECIMALS 2,
        valorunitariobaseicms   TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicms            TYPE p LENGTH 15 DECIMALS 2,
        valorlimitebase         TYPE p LENGTH 15 DECIMALS 2,
        valoricms               TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_documentorelativoultimaentr,


      BEGIN OF ty_ressarcimentoscomplementosi,
        documentorelativoultimaentr TYPE ty_documentorelativoultimaentr,
        documentoretencao           TYPE ty_documentoretencao,
        complemento                 TYPE ty_complemento,
        estoque                     TYPE ty_estoque,
        complementorestituicaocompl TYPE ty_complementorestituicaocompl,
      END OF ty_ressarcimentoscomplementosi,


      BEGIN OF ty_veiculos,
        tipooperacao       TYPE string,
        cnpjconcessionaria TYPE string,
        ufconcessionaria   TYPE string,
        chassiveiculo      TYPE string,
      END OF ty_veiculos,


      BEGIN OF ty_medicamentos,
        numerolotefabricacao TYPE string,
        quantidadeitemlote   TYPE p LENGTH 15 DECIMALS 2,
        datafabricacao       TYPE d,
        dataexpiracao        TYPE d,
        tipocalculoicms      TYPE string,
        tipoproduto          TYPE string,
        valor                TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_medicamentos,


      BEGIN OF ty_armas,
        tipoarma              TYPE string,
        numeroseriefabricacao TYPE string,
        descricao             TYPE string,
      END OF ty_armas,


      BEGIN OF ty_operacao,
        armas        TYPE STANDARD TABLE OF ty_armas WITH NON-UNIQUE DEFAULT KEY,
        medicamentos TYPE STANDARD TABLE OF ty_medicamentos WITH NON-UNIQUE DEFAULT KEY,
        veiculos     TYPE STANDARD TABLE OF ty_veiculos WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_operacao,


      BEGIN OF ty_inss,
        basecalculoinss                TYPE p LENGTH 15 DECIMALS 2,
        aliquotainss                   TYPE p LENGTH 15 DECIMALS 2,
        valorinss                      TYPE p LENGTH 15 DECIMALS 2,
        valorsubcontratadosinss        TYPE p LENGTH 15 DECIMALS 2,
        valorjuizoinss                 TYPE p LENGTH 15 DECIMALS 2,
        valoradicional                 TYPE p LENGTH 15 DECIMALS 2,
        valoradicionaljuizo            TYPE p LENGTH 15 DECIMALS 2,
        valorservicosativoaposentado15 TYPE p LENGTH 15 DECIMALS 2,
        valorservicosativoaposentado20 TYPE p LENGTH 15 DECIMALS 2,
        valorservicosativoaposentado25 TYPE p LENGTH 15 DECIMALS 2,
        valorbasedespesasinss          TYPE p LENGTH 15 DECIMALS 2,
        aliquotadespesasinss           TYPE p LENGTH 15 DECIMALS 2,
        valordespesasinss              TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_inss,


      BEGIN OF ty_ii,
        basecalculoii TYPE p LENGTH 15 DECIMALS 2,
        aliquotaii    TYPE p LENGTH 15 DECIMALS 2,
        valorii       TYPE p LENGTH 15 DECIMALS 2,
        valoriof      TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_ii,


      BEGIN OF ty_issqn,
        basecalculoissqn   TYPE p LENGTH 15 DECIMALS 2,
        aliquotaissqn      TYPE p LENGTH 15 DECIMALS 2,
        valorissqn         TYPE p LENGTH 15 DECIMALS 2,
        valorissretido     TYPE p LENGTH 15 DECIMALS 2,
        valorbaseissretido TYPE p LENGTH 15 DECIMALS 2,
        aliquotaissretido  TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_issqn,


      BEGIN OF ty_cofins,
        situacaotributariacofins    TYPE i,
        basecalculocofins           TYPE p LENGTH 15 DECIMALS 2,
        aliquotacofins              TYPE p LENGTH 15 DECIMALS 2,
        quantidadebasecalculocofins TYPE p LENGTH 15 DECIMALS 2,
        valorpautadocofins          TYPE p LENGTH 15 DECIMALS 2,
        valorcofins                 TYPE p LENGTH 15 DECIMALS 2,
        valorcofinsstretido         TYPE p LENGTH 15 DECIMALS 2,
        valorimportacaocofins       TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_cofins,


      BEGIN OF ty_pis,
        situacaotributariapis    TYPE i,
        basecalculopis           TYPE p LENGTH 15 DECIMALS 2,
        aliquotapis              TYPE p LENGTH 15 DECIMALS 2,
        quantidadebasecalculopis TYPE p LENGTH 15 DECIMALS 2,
        valorpautadopis          TYPE p LENGTH 15 DECIMALS 2,
        valorpis                 TYPE p LENGTH 15 DECIMALS 2,
        valorpisstretido         TYPE p LENGTH 15 DECIMALS 2,
        valorimportacaopis       TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_pis,


      BEGIN OF ty_ipi,
        periodoapuracaoipi     TYPE string,
        situacaotributariaipi  TYPE string,
        basecalculoipi         TYPE p LENGTH 15 DECIMALS 2,
        aliquotaipi            TYPE p LENGTH 15 DECIMALS 2,
        quantidadepautadaipi   TYPE p LENGTH 15 DECIMALS 2,
        valorpautadoipi        TYPE p LENGTH 15 DECIMALS 2,
        valoripi               TYPE p LENGTH 15 DECIMALS 2,
        valornaotributadoipi   TYPE p LENGTH 15 DECIMALS 2,
        valordevolvidoipi      TYPE p LENGTH 15 DECIMALS 2,
        valorbasetributadoipi  TYPE p LENGTH 15 DECIMALS 2,
        valorbaseisentoipi     TYPE p LENGTH 15 DECIMALS 2,
        valorbaseoutrosipi     TYPE p LENGTH 15 DECIMALS 2,
        selocontroleipi        TYPE string,
        quantidadeseloipi      TYPE p LENGTH 15 DECIMALS 2,
        enquandramentolegalipi TYPE string,
        classeenquadramentoipi TYPE string,
      END OF ty_ipi,


      BEGIN OF ty_icmsst,
        valorbaseicmsst                TYPE p LENGTH 15 DECIMALS 2,
        aliquotamarkup                 TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicmsst                 TYPE p LENGTH 15 DECIMALS 2,
        valoricmsst                    TYPE p LENGTH 15 DECIMALS 2,
        valoricmsstnaotributado        TYPE p LENGTH 15 DECIMALS 2,
        basecalculofcpst               TYPE p LENGTH 15 DECIMALS 2,
        percentualfcpst                TYPE p LENGTH 15 DECIMALS 2,
        valorfcpst                     TYPE p LENGTH 15 DECIMALS 2,
        basecalculoretidofcpst         TYPE p LENGTH 15 DECIMALS 2,
        percentualretidofcpst          TYPE p LENGTH 15 DECIMALS 2,
        valorfcpstretido               TYPE p LENGTH 15 DECIMALS 2,
        valorbaseicmsstnaotributado    TYPE p LENGTH 15 DECIMALS 2,
        valorbaseicmsfcpstnaotributado TYPE p LENGTH 15 DECIMALS 2,
        valoricmsfcpstnaotributado     TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_icmsst,


      BEGIN OF ty_diferido,
        aliquotadiferidoicms TYPE p LENGTH 15 DECIMALS 2,
        valordiferidoicms    TYPE p LENGTH 15 DECIMALS 2,
        valoroperacaoicms    TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_diferido,


      BEGIN OF ty_desonerado,
        valordesoneradoicms  TYPE p LENGTH 15 DECIMALS 2,
        motivodesoneradoicms TYPE string,
      END OF ty_desonerado,


      BEGIN OF ty_creditosimplesnacional,
        valorbaseicms TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicms  TYPE p LENGTH 15 DECIMALS 2,
        valoricms     TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_creditosimplesnacional,


      BEGIN OF ty_difal,
        valorbaseicmsdifal  TYPE p LENGTH 15 DECIMALS 2,
        aliquotadestinoicms TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicmsdifal   TYPE p LENGTH 15 DECIMALS 2,
        valoricmsdifal      TYPE p LENGTH 15 DECIMALS 2,
        percentualpartilha  TYPE p LENGTH 15 DECIMALS 2,
        valordestinoicms    TYPE p LENGTH 15 DECIMALS 2,
        valororigemicms     TYPE p LENGTH 15 DECIMALS 2,
        percentualfcp       TYPE p LENGTH 15 DECIMALS 2,
        valoricmsfcp        TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_difal,


      BEGIN OF ty_ativopermanente,
        itemativo           TYPE string,
        valorativoicms      TYPE p LENGTH 15 DECIMALS 2,
        valorativoicmsst    TYPE p LENGTH 15 DECIMALS 2,
        valorativoicmsdifal TYPE p LENGTH 15 DECIMALS 2,
        valorativoicmsfrete TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_ativopermanente,


      BEGIN OF ty_icms,
        situacaotributariaicmstaba TYPE i,
        situacaotributariaicmstabb TYPE i,
        valorbaseicms              TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicms               TYPE p LENGTH 15 DECIMALS 2,
        valoricms                  TYPE p LENGTH 15 DECIMALS 2,
        aliquotareducaoicms        TYPE p LENGTH 15 DECIMALS 2,
        valorreduzidoicms          TYPE p LENGTH 15 DECIMALS 2,
        valorbasetributadoicms     TYPE p LENGTH 15 DECIMALS 2,
        valorbaseisentoicms        TYPE p LENGTH 15 DECIMALS 2,
        valorbaseoutrosicms        TYPE p LENGTH 15 DECIMALS 2,
        valorbaseicmsnaocreditado  TYPE p LENGTH 15 DECIMALS 2,
        valoricmsnaocreditado      TYPE p LENGTH 15 DECIMALS 2,
        ativopermanente            TYPE ty_ativopermanente,
        difal                      TYPE ty_difal,
        creditosimplesnacional     TYPE ty_creditosimplesnacional,
        desonerado                 TYPE ty_desonerado,
        diferido                   TYPE ty_diferido,
      END OF ty_icms,


      BEGIN OF ty_imposto,
        icms    TYPE ty_icms,
        icmsst  TYPE ty_icmsst,
        ipi     TYPE ty_ipi,
        pis     TYPE ty_pis,
        cofins  TYPE ty_cofins,
        issqn   TYPE ty_issqn,
        ii      TYPE ty_ii,
        inss    TYPE ty_inss,
      END OF ty_imposto,


      BEGIN OF ty_centrocusto,
        codigo                         TYPE string,
        descricao                      TYPE string,
        dataatualizacaosistemacontabil TYPE d,
      END OF ty_centrocusto,


      BEGIN OF ty_naturezaoperacao,
        codigo    TYPE string,
        descricao TYPE string,
      END OF ty_naturezaoperacao,


      BEGIN OF ty_itens,
        numerosequencia                TYPE string,
        item                           TYPE ty_item,
        descricaocomplementar          TYPE string,
        codigofci                      TYPE string,
        codigoservicomunicipal         TYPE string,
        descricaoservicomunicipal      TYPE string,
        cfop                           TYPE string,
        cfopemitente                   TYPE string,
        cfopcomplemento                TYPE string,
        naturezaoperacao               TYPE ty_naturezaoperacao,
        codigoinformacaoadicional      TYPE string,
        unidademedida                  TYPE ty_unidademedida,
        quantidade                     TYPE string,
        valorunidade                   TYPE p LENGTH 15 DECIMALS 2,
        valortotal                     TYPE p LENGTH 15 DECIMALS 2,
        valordescontocomercial         TYPE p LENGTH 15 DECIMALS 2,
        valordescontozonafranca        TYPE p LENGTH 15 DECIMALS 2,
        valordespesaaduaneira          TYPE p LENGTH 15 DECIMALS 2,
        valorfrete                     TYPE p LENGTH 15 DECIMALS 2,
        valorseguro                    TYPE p LENGTH 15 DECIMALS 2,
        valoroutrasdespesas            TYPE p LENGTH 15 DECIMALS 2,
        valorcontabil                  TYPE p LENGTH 15 DECIMALS 2,
        valordeducao                   TYPE p LENGTH 15 DECIMALS 2,
        valormaterialterceiro          TYPE p LENGTH 15 DECIMALS 2,
        movimentacaofisica             TYPE string,
        controlemovimentacaofiscal     TYPE string,
        codigoespecificobeneficiofisca TYPE string,
        tipodocumentoimportacao        TYPE string,
        numerodocumentoimportacao      TYPE string,
        atoconcessionariodrawback      TYPE string,
        registroexportacao             TYPE string,
        origemcredito                  TYPE string,
        codigonaturezabasecalculocredi TYPE string,
        rateioproporcionalcredito      TYPE string,
        naturezareceita                TYPE string,
        naturezafrete                  TYPE string,
        tipofrete                      TYPE string,
        codigocontacontabilanalitica   TYPE string,
        centrocusto                    TYPE ty_centrocusto,
        categoriadocumentofiscal       TYPE string,
        numeropedidocliente            TYPE string,
        linhapedidocliente             TYPE string,
        codigoreferenciaintegracao     TYPE string,
        imposto                        TYPE ty_imposto,
        operacao                       TYPE ty_operacao,
        rescomplementosicmsst          TYPE STANDARD TABLE OF ty_ressarcimentoscomplementosi WITH NON-UNIQUE DEFAULT KEY,
        importacoes                    TYPE STANDARD TABLE OF ty_importacoes WITH NON-UNIQUE DEFAULT KEY,
        informacoesadicionais          TYPE STANDARD TABLE OF ty_informacoesadicionais WITH NON-UNIQUE DEFAULT KEY,
        numeroitememitente             TYPE string,
        codigoprodutoemitente          TYPE string,
        descricaoprodutoemitente       TYPE string,
        ncmemitente                    TYPE string,
        cestemitente                   TYPE string,
        situacaoicmstabaemitente       TYPE string,
        situacaoicmstabbemitente       TYPE string,
        valorbaseicmsnaocreditado      TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicmsnaotributado       TYPE string,
        valoricmsnaocreditado          TYPE p LENGTH 15 DECIMALS 2,
        valorbaseicmsstnaotributado    TYPE p LENGTH 15 DECIMALS 2,
        aliquotamarkupnaotributado     TYPE p LENGTH 15 DECIMALS 2,
        aliquotaicmssubstnaotributado  TYPE p LENGTH 15 DECIMALS 2,
        valoricmssubstnaotributado     TYPE p LENGTH 15 DECIMALS 2,
        valorbaseicmsfcpstnaotributado TYPE p LENGTH 15 DECIMALS 2,
        percentualfcpstnaotributado    TYPE p LENGTH 15 DECIMALS 2,
        valoricmsfcpstnaotributado     TYPE p LENGTH 15 DECIMALS 2,
        valortotalsubempreitada        TYPE p LENGTH 15 DECIMALS 2,
        valortotalserviconaotributado  TYPE p LENGTH 15 DECIMALS 2,
        valormaterialproprio           TYPE p LENGTH 15 DECIMALS 2,
        valortotalcobradonometerceiro  TYPE p LENGTH 15 DECIMALS 2,
        valordescontoenergiainjetada   TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_itens,


      BEGIN OF ty_pagamentos,
        numerosequencia                TYPE string,
        formapagamento                 TYPE string,
        valorpagamento                 TYPE p LENGTH 15 DECIMALS 2,
        valortroco                     TYPE p LENGTH 15 DECIMALS 2,
        tipointegracao                 TYPE string,
        cnpjcredenciadoracartao        TYPE string,
        bandeiraoperadoracartao        TYPE string,
        numeroautorizacaooperacaocarta TYPE string,
      END OF ty_pagamentos,


      BEGIN OF ty_parcelas,
        numeroparcela  TYPE string,
        datavencimento TYPE d,
        datapagamento  TYPE d,
        valorprincipal TYPE p LENGTH 15 DECIMALS 2,
        valormulta     TYPE p LENGTH 15 DECIMALS 2,
        valorjuros     TYPE p LENGTH 15 DECIMALS 2,
        valorpago      TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_parcelas,


      BEGIN OF ty_fatura,
        emitente              TYPE string,
        titulocredito         TYPE string,
        numero                TYPE string,
        valor                 TYPE string,
        numeroparcelas        TYPE string,
        descricaocomplementar TYPE string,
      END OF ty_fatura,


      BEGIN OF ty_cobranca,
        fatura     TYPE ty_fatura,
        parcelas   TYPE STANDARD TABLE OF ty_parcelas WITH NON-UNIQUE DEFAULT KEY,
        pagamentos TYPE STANDARD TABLE OF ty_pagamentos WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_cobranca,


      BEGIN OF ty_exportacao,
        paisembarquecodigoibge TYPE string,
        estadoembarque         TYPE string,
        localembarque          TYPE string,
        localdespacho          TYPE string,
      END OF ty_exportacao,


      BEGIN OF ty_transportadora,
        codigo                         TYPE string,
        nome                           TYPE string,
        nomefantasia                   TYPE string,
        cnpj                           TYPE string,
        cpf                            TYPE string,
        inscricaoestadual              TYPE string,
        inscricaomunicipal             TYPE string,
        inscricaosuframa               TYPE string,
        codigocnae                     TYPE string,
        indcprb                        TYPE string,
        ativo                          TYPE string,
        endereco                       TYPE string,
        numero                         TYPE string,
        complemento                    TYPE string,
        bairro                         TYPE string,
        cep                            TYPE string,
        paiscodigoibge                 TYPE string,
        municipiocodigoibge            TYPE string,
        ddd                            TYPE string,
        telefone                       TYPE string,
        email                          TYPE string,
        indoptantesimplesnacional      TYPE string,
        indicadornif                   TYPE string,
        nif                            TYPE string,
        indicadorcontribuinteicms      TYPE string,
        indicadorcontribuinteipi       TYPE string,
        codigoformatribrendbeneficiari TYPE string,
        codigoinfbeneficiariosrendex   TYPE string,
        tipoparceiro                   TYPE string,
        tipoclienteicms11503           TYPE string,
        obras                          TYPE STANDARD TABLE OF ty_obras WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_transportadora,


      BEGIN OF ty_transporte,
        transportadora     TYPE ty_transportadora,
        placaveiculo       TYPE string,
        viatransporte      TYPE string,
        especievolume      TYPE string,
        quantidade         TYPE string,
        pesobruto          TYPE p LENGTH 15 DECIMALS 2,
        pesoliquido        TYPE p LENGTH 15 DECIMALS 2,
        marca              TYPE string,
        numero             TYPE string,
        estado             TYPE string,
        tipofrete          TYPE string,
        naturezafrete      TYPE string,
        tipocte            TYPE string,
        chavecte           TYPE string,
        chavectereferencia TYPE string,
        exportacao         TYPE ty_exportacao,
      END OF ty_transporte,


      BEGIN OF ty_descontodespesaoutros,
        valordescontolivrecomercio TYPE p LENGTH 15 DECIMALS 2,
        valordescontozonafranca    TYPE p LENGTH 15 DECIMALS 2,
        valortotaldesconto         TYPE p LENGTH 15 DECIMALS 2,
        valoroutrasdespesas        TYPE p LENGTH 15 DECIMALS 2,
        valorfrete                 TYPE p LENGTH 15 DECIMALS 2,
        valorseguro                TYPE p LENGTH 15 DECIMALS 2,
        valordeducao               TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_descontodespesaoutros,


      BEGIN OF ty_irrf,
        valorirrf     TYPE p LENGTH 15 DECIMALS 2,
        valorbaseirrf TYPE p LENGTH 15 DECIMALS 2,
        aliquotairrf  TYPE p LENGTH 15 DECIMALS 2,
      END OF ty_irrf,


      BEGIN OF ty_totais,
        valormercadorias      TYPE p LENGTH 15 DECIMALS 2,
        valorservicos         TYPE p LENGTH 15 DECIMALS 2,
        valordocumento        TYPE p LENGTH 15 DECIMALS 2,
        icms                  TYPE ty_icms,
        icmsst                TYPE ty_icmsst,
        ipi                   TYPE ty_ipi,
        pis                   TYPE ty_pis,
        cofins                TYPE ty_cofins,
        inss                  TYPE ty_inss,
        issqn                 TYPE ty_issqn,
        irrf                  TYPE ty_irrf,
        descontodespesaoutros TYPE ty_descontodespesaoutros,
      END OF ty_totais,


      BEGIN OF ty_main,
        codigoempresa                  TYPE string,
        codigocontribuinte             TYPE string,
        parceiro                       TYPE ty_parceiro,
        inscricaomunicipal             TYPE string,
        inscricaoestadualsubstituto    TYPE string,
        operacao                       TYPE string,
        emitidacontribuinte            TYPE string,
        finalidadenotafiscal           TYPE string,
        serie                          TYPE string,
        subserie                       TYPE string,
        modelo                         TYPE string,
        modeloservico                  TYPE string,
        numerodocumento                TYPE string,
        chavenfe                       TYPE string,
        dataemissao                    TYPE d,
        dataentradasaida               TYPE d,
        dataexecucaoservico            TYPE d,
        localexecucaoservico           TYPE string,
        periodoescrituracao            TYPE d,
        situacao                       TYPE string,
        datacancelamento               TYPE d,
        motivocancelamento             TYPE string,
        tipopagamento                  TYPE string,
        tipoconsumo                    TYPE string,
        codigoclasseconsumo            TYPE string,
        tipoligacao                    TYPE string,
        grupotensao                    TYPE string,
        codigoobra                     TYPE string,
        codigoobrafilial               TYPE string,
        codigocno                      TYPE string,
        municipiorecolhimentoisscodigo TYPE string,
        municipioexecucaoservicocodigo TYPE string,
        operacaoconsumidor             TYPE string,
        presencacomprador              TYPE string,
        inscricaoestadualdestinatario  TYPE string,
        notafiscalativo                TYPE string,
        codigoreferenciaintegracao     TYPE string,
        numerolancamentocontabil       TYPE string,
        CodigoContaAnaliticaContabil   TYPE string,
        categoriadocfiscal             TYPE string,
        indintermediario               TYPE string,
        numeroserieequipamentosat      TYPE string,
        datainicioprestacaoservico     TYPE d,
        dataterminoprestacaoservico    TYPE d,
        totais                         TYPE ty_totais,
        transporte                     TYPE ty_transporte,
        cobranca                       TYPE ty_cobranca,
        informacoesadicionais          TYPE ty_informacoesadicionais,
        itens                          TYPE STANDARD TABLE OF ty_itens WITH NON-UNIQUE DEFAULT KEY,
        parceiros                      TYPE STANDARD TABLE OF ty_parceiros WITH NON-UNIQUE DEFAULT KEY,
        impostosretidos                TYPE STANDARD TABLE OF ty_impostosretidos WITH NON-UNIQUE DEFAULT KEY,
        complementoscte                TYPE STANDARD TABLE OF ty_complementosconhecimentotra WITH NON-UNIQUE DEFAULT KEY,
        notasfiscaiscte                TYPE STANDARD TABLE OF ty_notasfiscaisconhecimentotra WITH NON-UNIQUE DEFAULT KEY,
        observacoes                    TYPE STANDARD TABLE OF ty_observacoes WITH NON-UNIQUE DEFAULT KEY,
      END OF ty_main,
      BEGIN OF ty_docs,
        docunm TYPE i_br_nfdocument-br_notafiscal,
      END OF ty_docs,
      BEGIN OF ty_bkpf,
        companycode               TYPE i_journalentry-companycode,
        fiscalyear                TYPE i_journalentry-fiscalyear,
        accountingdocument        TYPE i_journalentry-accountingdocument,
        originalreferencedocument TYPE i_journalentry-originalreferencedocument,
      END OF ty_bkpf,
      BEGIN OF ty_bseg,
        companycode                TYPE i_glaccountlineitemrawdata-companycode,
        fiscalyear                 TYPE i_glaccountlineitemrawdata-fiscalyear,
        accountingdocument         TYPE i_glaccountlineitemrawdata-accountingdocument,
        ledgergllineitem           TYPE i_glaccountlineitemrawdata-ledgergllineitem,
        financialaccounttype       TYPE i_glaccountlineitemrawdata-financialaccounttype,
        controllingdebitcreditcode TYPE i_glaccountlineitemrawdata-controllingdebitcreditcode,
        netduedate                 TYPE i_glaccountlineitemrawdata-netduedate,
        invoicereference           TYPE i_glaccountlineitemrawdata-invoicereference,
      END OF ty_bseg,
      BEGIN OF ty_withtax,
        companycode                 TYPE i_withholdingtaxitem-companycode,
        fiscalyear                  TYPE i_withholdingtaxitem-fiscalyear,
        accountingdocument          TYPE i_withholdingtaxitem-accountingdocument,
        accountingdocumentitem      TYPE i_withholdingtaxitem-accountingdocumentitem,
        withholdingtaxtype          TYPE i_withholdingtaxitem-withholdingtaxtype,
        withholdingtaxcode          TYPE i_withholdingtaxitem-withholdingtaxcode,
        whldgtaxbaseamtincocodecrcy TYPE i_withholdingtaxitem-whldgtaxbaseamtincocodecrcy,
        whldgtaxamtincocodecrcy     TYPE i_withholdingtaxitem-whldgtaxamtincocodecrcy,
        withholdingtaxpercent       TYPE i_withholdingtaxitem-withholdingtaxpercent,
        clearingaccountingdocument  TYPE i_withholdingtaxitem-clearingaccountingdocument,
        clearingdate                TYPE i_withholdingtaxitem-clearingdate,
      END OF ty_withtax,

      tty_docs   TYPE STANDARD TABLE OF ty_docs,
      tty_branch TYPE STANDARD TABLE OF i_br_businessplace-branch,
      BEGIN OF ty_sel,
        company  TYPE i_br_businessplace-companycode,
        branch   TYPE i_br_businessplace-branch,
        creation TYPE RANGE OF i_br_nfdocument-creationdate,
        category TYPE RANGE OF i_br_nfdocument-br_nfdocumenttype,
        document TYPE RANGE OF i_br_nfdocument-br_notafiscal,
        docdate  TYPE RANGE OF i_br_nfdocument-br_nfissuedate,
        pstdate  TYPE RANGE OF i_br_nfdocument-br_nfpostingdate,
        dsaient  TYPE RANGE OF i_br_nfdocument-br_nfarrivalordeparturedate,
        changed  TYPE RANGE OF i_br_nfdocument-lastchangedate,
      END OF ty_sel,
      BEGIN OF ty_nfitem,
        nf                   TYPE i_br_nfitem,
        product              TYPE i_product-product,
        producttype          TYPE i_product-producttype,
        baseunit             TYPE i_product-baseunit,
        alternativeunit      TYPE i_productunitsofmeasure-alternativeunit,
        quantitynumerator    TYPE i_productunitsofmeasure-quantitynumerator,
        plant                TYPE c LENGTH 4,
        iscoproduct          TYPE c LENGTH 1,
        referenceproducttype TYPE i_producttype-referenceproducttype,
        UnitOfMeasureISOCode TYPE I_UnitOfMeasure-UnitOfMeasureISOCode,
        UnitOfMeasure_E      TYPE I_UnitOfMeasure-UnitOfMeasure_E,
      END OF ty_nfitem.
    METHODS:
      main_process.
